version: 2.1
orbs:
    aws-s3: circleci/aws-s3@1.0.13
    aws-code-deploy: circleci/aws-code-deploy@0.0.12

jobs:
    build:
        docker:
            - image: circleci/openjdk:11-jdk
        
        steps:
            - checkout
            - run:
                  name: [소스 압축]
                  command: |
                      zip back.zip -r ./*
                      mkdir -p deploy	
                      mv back.zip deploy/back.zip

            - persist_to_workspace:
                  root: .
                  paths: deploy
    
    deploy:
        docker:
            - image: circleci/python:2.7
        
        steps:
            - attach_workspace:
                  at: .

            - aws-s3/copy:
                  from: deploy/*
                  to: 's3://jhpark153-deploy'
                  aws-region: AWS_DEFAULT_REGION

            - aws-code-deploy/deploy-bundle:
                  application-name: jhpark153-deploy
                  deployment-group: jhpark153-deploy-group
                  deployment-config: CodeDeployDefault.AllAtOnce
                  bundle-bucket: jhpark153-deploy
                  bundle-key: back
                  bundle-type: zip


workflows:
    version: 2.1
    
    build-deploy:
        jobs:
            - build
            - deploy:
                  context: DEVOPS_TEST
                  requires:
                      - build